(function(){
'use strict';
const D=window.MysteryData,E=window.MysteryEngine,S=window.MysteryScene;
const app=document.getElementById('app'),dialog=document.getElementById('dialog'),content=document.getElementById('dialog-content'),toast=document.getElementById('toast');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=E.newState(),saveAvailable=true,returnFocus='',filmIndex=0,filmPaused=false,filmTimer,toastTimer,sceneFocus=null,sceneFocusToken=0,pendingLegacyBackup='';
const workspaces={},sheetState={},workspaceViews={};
let renderedView='',renderEpoch=0,scrollInputEpoch=0,dialogViewport=null,returnFocusElement=null;
for(const event of ['wheel','touchmove'])window.addEventListener(event,()=>{scrollInputEpoch++;},{passive:true});
window.addEventListener('keydown',event=>{if(['PageUp','PageDown','Home','End','ArrowUp','ArrowDown',' '].includes(event.key))scrollInputEpoch++;});
try{const raw=localStorage.getItem(E.SAVE_KEY);if(raw){const parsed=JSON.parse(raw);state=E.normalizeSave(parsed);if(parsed.version===2&&!localStorage.getItem('record-and-body.future.legacy-v2')){pendingLegacyBackup=raw;localStorage.setItem('record-and-body.future.legacy-v2',raw);pendingLegacyBackup='';}}}catch(_){saveAvailable=false;}
const c=()=>D.cases[state.current],p=()=>state.cases[state.current];
const voluntary=()=>c().interactionVersion===4;
const hasRecord=(x=c(),q=p())=>x.interactionVersion===4?(q.resolved||[]).length>0:q.solved;
const paragraphs=value=>(Array.isArray(value)?value:[value]).filter(Boolean).map(t=>`<p>${esc(t)}</p>`).join('');
function persist(){try{if(pendingLegacyBackup){localStorage.setItem('record-and-body.future.legacy-v2',pendingLegacyBackup);pendingLegacyBackup='';}localStorage.setItem(E.SAVE_KEY,E.serialize(state));saveAvailable=true;}catch(_){saveAvailable=false;}}
function act(a,draw=true){E.apply(state,a);persist();if(draw)render();}
function imageAttrs(src){const size=D.imageSizes?.[String(src||'').split('?')[0]];return size?`width="${size[0]}" height="${size[1]}"`:'';}
function btn(label,action,attrs='',cls='quiet'){return `<button type="button" class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;}
function notice(text){clearTimeout(toastTimer);toast.textContent=text;toast.classList.add('visible');toastTimer=setTimeout(()=>toast.classList.remove('visible'),6000);}
function opt(id,text,value){return `<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`;}
function chooseLocation(id){workspaces[state.current]='inspect';sheetState[state.current]=true;sceneFocus={id,token:++sceneFocusToken};act({type:'location',id});}
function locations(){return (c().locations||[]).filter(l=>E.available(c(),p(),l));}
function seen(){return c().evidence.filter(e=>p().seen.includes(e.id));}
function locationFor(anchor){return locations().find(l=>(l.anchor||l.id)===anchor||(l.evidenceIds||[]).includes(anchor));}
// Keep investigation controls under the player while rebuilding their surrounding text.
// The temporary height avoids browser clamping during the scene's detach/remount.
function viewportSnapshot(){
 const active=document.activeElement, focusKey=active?.getAttribute('data-focus-key')||'';
 const nested=[...app.querySelectorAll('[id],[data-scroll-key],.location-list,.evidence-index,.reference-rail')].filter(el=>el.scrollTop||el.scrollLeft).map(el=>({id:el.id,key:el.dataset.scrollKey,cls:el.className,top:el.scrollTop,left:el.scrollLeft}));
 return {x:window.scrollX||0,y:window.scrollY||0,focusKey,anchorTop:focusKey&&!focusKey.startsWith('scene-')?active.getBoundingClientRect().top:null,nested};
}
function focusKeyElement(key){return key?[...app.querySelectorAll('[data-focus-key]')].find(el=>el.dataset.focusKey===key):null;}
function restoreViewport(v,anchor=true){
 if(!v)return;
 for(const n of v.nested||[]){const el=n.id?document.getElementById(n.id):n.key?[...app.querySelectorAll('[data-scroll-key]')].find(e=>e.dataset.scrollKey===n.key):[...app.querySelectorAll('[class]')].find(e=>e.className===n.cls);if(el){el.scrollTop=n.top;el.scrollLeft=n.left;}}
 const el=anchor?focusKeyElement(v.focusKey):null;
 const y=el&&v.anchorTop!==null?(window.scrollY||0)+el.getBoundingClientRect().top-v.anchorTop:v.y;
 window.scrollTo({left:v.x,top:Math.max(0,y),behavior:'instant'});
}
function workspace(){return workspaces[state.current]||(p().tab==='inspect'?'inspect':'inference');}
function switchWorkspace(next){workspaceViews[state.current+'/'+workspace()]=viewportSnapshot();workspaces[state.current]=next;render();restoreViewport(workspaceViews[state.current+'/'+next],false);}
function render(){
 clearTimeout(filmTimer);const view=[state.screen,state.current,state.screen==='desk'?workspace()+'/'+p().tab:''].join('/'),sameView=view===renderedView,viewport=sameView?viewportSnapshot():null,epoch=++renderEpoch,inputEpoch=scrollInputEpoch;
 const focused=document.activeElement?.getAttribute('data-focus-key');app.style.minHeight=sameView?app.getBoundingClientRect().height+'px':'';S?.beforeRender();document.body.dataset.case=state.current;document.body.dataset.screen=state.screen;
 app.innerHTML=state.screen==='title'?title():state.screen==='ending'?ending():state.screen==='epilogue'?epilogue():state.screen==='opening'?opening():desk();
 const host=app.querySelector('[data-scene-root]');if(host&&S){const ls=locations();S.mount(host,{caseId:state.current,investigationActions:p().actions||[],investigationState:p().objectStates||{},evidence:ls.map((l,i)=>({id:l.anchor||l.id,title:l.name,hotspot:l.name,number:String(i+1)})),seen:voluntary()?[]:ls.filter(l=>(l.evidenceIds||[]).some(id=>p().seen.includes(id))).map(l=>l.anchor||l.id),selected:ls.find(l=>l.id===p().location)?.anchor||p().location,focusLocation:sceneFocus,cinematicShot:state.screen==='opening'?c().opening?.[filmIndex]?.id:undefined,onEvidence:anchor=>{const l=locationFor(anchor);if(l){chooseLocation(l.id);document.getElementById('location-panel')?.focus({preventScroll:true});}}});}
 if(focused)app.querySelectorAll('[data-focus-key]').forEach(el=>{if(el.dataset.focusKey===focused)el.focus({preventScroll:true});});
 renderedView=view;restoreViewport(viewport);if(!sameView)window.scrollTo({left:0,top:0,behavior:'instant'});
 const settle=()=>{if(epoch!==renderEpoch)return;app.style.minHeight='';if(inputEpoch===scrollInputEpoch)restoreViewport(viewport);};
 if(window.requestAnimationFrame)window.requestAnimationFrame(settle);else settle();
 if(state.screen==='opening'&&!filmPaused&&!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches){const index=filmIndex;const schedule=()=>{if(state.screen!=='opening'||filmPaused||filmIndex!==index)return;if(host?.dataset.viewState==='loading')filmTimer=setTimeout(schedule,250);else filmTimer=setTimeout(nextShot,7500);};schedule();}
}
function title(){return `<main class="title-screen"><header class="title-mast"><span>二つの事件の調査記録</span>${btn('遊び方','help')}</header><section class="title-intro"><p class="title-folio">記録室 <span class="edition-label">自由調査版 · v5</span></p><h1>${D.title}</h1><p class="tagline">${D.subtitle}</p></section>${state.revisionNotice?'<p class="migration-notice control-help" role="status">v5では近未来の事件を作り直しました。v4の村の進行とメモは残しています。旧版の近未来は別保存のまま、新しい調査を初めからにしています。v1〜v3の村はメモを残して初めからになります。<a href="future-v2.html">旧近未来の保存を開く</a></p>':''}<section class="case-files">${D.caseIds.map(id=>{const x=D.cases[id],q=state.cases[id];return `<article class="case-file ${x.accent}"><div class="file-tab">事件 ${x.number}<span>${q.solved?'解決済み':(q.seen.length||q.actions?.length)?'調査中':'未調査'}</span></div><img class="file-scene" src="${x.scene}?v=${D.version}" ${imageAttrs(x.scene)} alt="${esc(x.era)}の配置図"><div class="file-content"><p class="era">${x.era}</p><h2>${x.title}</h2><p>${x.intro}</p><div class="file-footer">${btn((q.seen.length||q.actions?.length||q.openingSeen)?'調査を続ける':'物語を始める','open',`data-case-id="${id}"`,'primary')}${hasRecord(x,q)?btn('解決記録','ending',`data-case-id="${id}"`):''}</div></div></article>`;}).join('')}</section><footer class="title-footer"><p class="save-status">${saveAvailable?'このブラウザーに自動保存します':'自動保存を使えません。進行をファイルに保存してください'}</p>${btn('進行をファイルに保存','export')}${btn('保存ファイルを読込','import')}${D.caseIds.every(id=>state.cases[id].solved)?btn('二つの記録を閉じる','epilogue'):''}<input id="save-import" type="file" accept="application/json,.json" hidden></footer></main>`;}
function scene(film=false){const x=c(),config=S?.config?.[x.id];return `<section class="scene-wrap scene3d-wrap ${film?'cinematic-scene':''}" data-scene-root data-view-state="map"><div class="scene-caption"><h2>${film?(x.id==='village'?'祭りの日、故郷へ':'市民資料館'):'現場を調べる'}</h2><div class="scene-mode"><button data-view-mode="3d" aria-pressed="true">3D模型</button><button data-view-mode="2d" aria-pressed="false">見取り図</button></div></div><div class="scene3d-status-row"><p class="scene3d-status" role="status">立体模型を準備中</p><button data-view-retry hidden>3Dを再試行</button></div><div data-scene-mount class="scene3d-mount"></div><div class="scene-map"><img src="${x.scene}?v=${D.version}" ${imageAttrs(x.scene)} alt="建物、戸口、人の位置を示す現場の配置図">${!film?locations().map((l,i)=>{const e=x.evidence.find(e=>(l.evidenceIds||[]).includes(e.id));const pos=l.pos||e?.pos||[18+i*12,60];return btn(`<span class="map-pin-dot" aria-hidden="true"></span><span class="map-pin-label">${esc(l.name)}</span>`,'location',`data-id="${l.id}" data-focus-key="map-${l.id}" style="left:${pos[0]}%;top:${pos[1]}%" aria-label="${esc(l.name)}" aria-pressed="${p().location===l.id}"`,'evidence-pin');}).join(''):''}</div>${!film?`<details class="scene3d-toolbar"><summary>視点・模型の操作</summary><div class="scene3d-camera-buttons" role="group" aria-label="模型の視点・見え方（観察用）">${[['left','↶ 左'],['right','右 ↷'],['in','＋'],['out','−'],['reset','全景']].map(([id,text])=>`<button data-view-control="${id}" aria-label="視点 ${text}">${text}</button>`).join('')}${x.id==='village'?'<button data-view-control="roof">屋根を外す</button><button data-view-control="cover" aria-label="模型の白布の見え方を変える（観察用）">模型の白布をめくる</button>':''}</div><div class="viewpoint-buttons">${(config?.viewpoints||[]).map(v=>`<button data-view-control="view:${v.id}">${esc(v.label)}</button>`).join('')}</div></details>`:''}<div class="scene3d-context"><p id="scene-controls-help">${film?'静止した人形と模型を使った場面紹介です。音声はありません。':'ドラッグ・矢印キーで回転、＋/−で拡大。丸い印で場所を選べます。'}</p>${!film?'<p>人形は現在の位置です。見取り図でも調査できます。</p>':''}</div></section>`;}
function desk(){const x=c(),q=p(),v4=voluntary(),ws=workspace(),tabs=x.reconstruction?[['build','記録を比べる'],['report','相手に確かめる'],['reconstruct','説明を残す']]:v4?[['build','記録を比べる'],['report','相手に確かめる']]:[['build','証言を問い直す'],['report','推理をつなぐ']];return `<div class="desk-shell field-shell ${x.accent}" data-workspace="${ws}"><header class="desk-header">${btn('事件一覧','home','data-focus-key="home"')}<div class="case-heading"><h1>${x.title}</h1></div><nav class="workspace-nav" aria-label="調査の画面">${[['inspect','現場'],['notebook','手帳'],['inference','推理']].map(([id,label])=>btn(label,'workspace',`data-workspace="${id}" data-focus-key="workspace-${id}" aria-current="${ws===id?'page':'false'}"`,'workspace-link')).join('')}</nav>${btn('メニュー','menu','data-focus-key="menu"','menu-button quiet')}</header><main class="desk-content"><div class="field-stage" ${ws!=='inspect'?'inert aria-hidden="true"':''}>${scene()}${v4?inspectVoluntary():inspect()}</div><section class="workspace-panel" ${ws==='inspect'?'hidden':''} aria-label="${ws==='notebook'?'調査手帳':'推理の作業台'}" data-scroll-key="workspace-${ws}"><header class="workspace-heading"><h2>${ws==='notebook'?'調査手帳':'推理の作業台'}</h2>${btn('現場へ戻る','workspace','data-workspace="inspect" data-focus-key="return-scene"')}</header><nav class="desk-tabs" aria-label="調査の方法" ${ws!=='inference'?'hidden':''}>${btn('現場を調べる','tab','data-tab="inspect" data-focus-key="tab-inspect"','tab')}${tabs.map(([id,label])=>btn(label,'tab',`data-tab="${id}" data-focus-key="tab-${id}" aria-current="${q.tab===id?'page':'false'}"`,q.tab===id?'tab active':'tab')).join('')}</nav>${ws==='notebook'?`${notebook()}<section class="personal-notes"><label for="notes-input">自分のメモ</label><textarea id="notes-input" rows="5" maxlength="5000" data-change="notes">${esc(q.notes)}</textarea><small>自動保存 · 最大5,000文字</small></section>`:ws==='inference'?(v4?(q.tab==='report'?presentation():q.tab==='reconstruct'?reconstruction():comparison()):(q.tab==='report'?report():deductions())):''}</section></main></div>`;}
function fieldMenu(){show('メニュー',`<p class="save-status">${saveAvailable?'このブラウザーに自動保存しています':'自動保存できません。ファイル保存を使ってください'}</p><div class="menu-actions">${btn('事件の前提','premise')}${btn('会話履歴','history')}${btn('自分のメモ','notes')}${btn('遊び方','help')}${btn('ヒント（任意）','hints')}${c().opening?.length?btn('序幕を再生','replay'):''}${btn('進行をファイルに保存','export')}${btn('保存ファイルを読込','import')}${hasRecord()?btn('解決記録を読む','ending'):''}${btn('この事件を初めから','reset')}</div>`);}
function objectView(object){const view=(object.views||[]).filter(v=>E.available(c(),p(),v)).at(-1);return {text:view?.text??object.description,image:view?.image??object.image,imageAlt:view?.imageAlt??object.imageAlt};}
function observation(scope=''){const r=p().lastResult;if(!r)return '';const records=seen().filter(e=>(r.evidence||[]).includes(e.id));return `<section class="observation-result" id="${scope?scope+'-':''}observation-result" tabindex="-1" role="status" aria-live="polite" aria-atomic="true"><p class="scene-eyebrow">直前の観察・応答</p><h3>${esc(r.title||'確かめたこと')}</h3>${paragraphs(r.body)}${r.image?`<figure class="observation-figure"><img class="evidence-detail" src="${esc(r.image)}" ${imageAttrs(r.image)} alt="${esc(r.imageAlt||'調べた対象の様子')}"></figure>`:''}${records.length?`<div class="result-records"><span>手帳に残した記録</span>${records.map(e=>btn(esc(e.title),'show-evidence',`data-id="${esc(e.id)}" data-focus-key="result-${esc(e.id)}"`,'reference-entry')).join('')}</div>`:''}</section>`;}
function inspectVoluntary(){const ls=locations(),l=ls.find(l=>l.id===p().location),objects=(c().objects||[]).filter(o=>o.location===l?.id&&E.available(c(),p(),o)),object=objects.find(o=>o.id===p().selectedObject),view=object?objectView(object):null,actions=object?(c().actions||[]).filter(a=>a.object===object.id&&(!object.actions||object.actions.includes(a.id))&&E.available(c(),p(),a)):[],person=object&&(c().suspects||[]).some(person=>person.id===object.id),expanded=sheetState[state.current]!==false;return `<div class="field-location"><label for="field-location-select">場所</label><select id="field-location-select" data-change="field-location" data-focus-key="field-location">${opt('','調べる場所を選ぶ',p().location)}${ls.map(l=>opt(l.id,l.name,p().location)).join('')}</select>${btn('場所一覧','locations','data-focus-key="locations"')}</div><section class="location-panel field-sheet ${person?'dialogue-sheet':''} ${expanded?'is-expanded':'is-collapsed'}" id="location-panel" tabindex="-1" data-scroll-key="field-sheet"><header class="field-sheet-heading"><div><p class="scene-eyebrow">${person?'話を聞く':'現在の場所'}</p><h2>${esc(l?.name||'どこから調べよう？')}</h2></div><div class="sheet-tools">${hasRecord()?btn('解決記録','ending','data-focus-key="ending"'):''}${person?btn('会話履歴','history','data-focus-key="history"'):''}${btn(expanded?'現場を広く見る':'調査を開く','sheet-toggle',`data-focus-key="sheet-toggle" aria-expanded="${expanded}" aria-controls="field-sheet-body"`)}</div></header><div id="field-sheet-body" ${!expanded?'hidden':''}>${l?`<p class="location-description">${esc(l.description)}</p><div class="object-cards" role="group" aria-label="${esc(l.name)}の対象">${objects.map(o=>btn(esc(o.name),'object',`data-id="${esc(o.id)}" data-focus-key="object-${esc(o.id)}" aria-pressed="${object?.id===o.id}"`,'object-card')).join('')}</div>${object?`<article class="object-surface" aria-labelledby="object-title"><div class="object-text"><h3 id="object-title">${esc(object.name)}</h3>${p().lastResult?observation('field'):`${paragraphs(view.text)}${view.image?`<figure class="object-figure"><img class="evidence-detail" src="${esc(view.image)}" ${imageAttrs(view.image)} alt="${esc(view.imageAlt||object.name)}"></figure>`:''}`}</div><div class="search-actions" role="group" aria-label="${esc(object.name)}への行動">${actions.map(a=>btn(esc(a.label),'interact',`data-id="${esc(a.id)}" data-focus-key="interact-${esc(a.id)}"`,'search-action')).join('')}${person?btn('記録を示して話す','talk-records',`data-id="${esc(object.id)}" data-focus-key="talk-records-${esc(object.id)}"`):''}</div></article>`:'<p class="control-help">気になった物や人を選んでください。</p>'}`:'<p>丸い印か場所名を選ぶと、調べる対象が表示されます。</p>'}</div></section>`;}
function recordOptions(value,empty='記録を選ぶ'){return opt('',empty,value)+seen().map(e=>opt(e.id,e.title,value)).join('');}
function comparison(){const q=p().compare||{};return `<div class="inquiry-layout"><section class="inquiry-sheet"><p class="scene-eyebrow">手帳を開く</p><h2>二つの記録を比べる</h2><div class="comparison-fields">${[['left','一つ目の記録'],['right','二つ目の記録']].map(([field,label])=>`<label for="compare-${field}">${label}<select id="compare-${field}" data-change="compare-select" data-field="${field}" data-focus-key="compare-${field}">${recordOptions(q[field])}</select></label>`).join('')}</div>${btn('二つを比べる','compare','data-focus-key="compare-submit"','primary')}<div class="comparison-originals">${[q.left,q.right].map(id=>seen().find(e=>e.id===id)).filter(Boolean).map(e=>`<article class="comparison-original">${evidenceBody(e)}</article>`).join('')}</div>${observation()}</section>${reference()}</div>`;}
function presentation(){const q=p().presentation||{},people=c().suspects||c().people||[];return `<div class="inquiry-layout"><section class="inquiry-sheet"><p class="scene-eyebrow">話を聞く</p><h2>相手に確かめる</h2><div class="presentation-fields"><label for="presentation-person">話す相手<select id="presentation-person" data-change="presentation-select" data-field="person" data-focus-key="presentation-person">${opt('','相手を選ぶ',q.person)}${people.map(person=>opt(person.id,person.name||person.label,q.person)).join('')}</select></label><label for="presentation-topic">確かめること<select id="presentation-topic" data-change="presentation-select" data-field="topic" data-focus-key="presentation-topic">${opt('','話題を選ぶ',q.topic)}${(c().topics||[]).filter(topic=>E.available(c(),p(),topic)).map(topic=>opt(topic.id,topic.label,q.topic)).join('')}</select></label></div><fieldset class="presentation-records"><legend>示す記録（なくても話せます・二つまで）</legend><div class="comparison-fields">${[['evidenceA','一つ目'],['evidenceB','二つ目']].map(([field,label])=>`<label for="presentation-${field}">${label}<select id="presentation-${field}" data-change="presentation-select" data-field="${field}" data-focus-key="presentation-${field}">${recordOptions(q[field],'記録を示さない')}</select></label>`).join('')}</div></fieldset>${btn('この内容で話す','present','data-focus-key="present-submit"','primary')}${observation()}</section>${reference()}</div>`;}
function showHistory(){const replay=E.newState(),id=state.current,entries=[];replay.current=id;replay.screen='desk';for(const event of p().history||[]){if(event.type==='interact'){const action=c().actions.find(a=>a.id===event.id),o=c().objects.find(o=>o.id===action?.object);if(!o)continue;E.apply(replay,{type:'location',id:o.location});E.apply(replay,{type:'object',id:o.id});E.apply(replay,event);if((c().suspects||[]).some(person=>person.id===o.id))entries.push({speaker:o.name,result:replay.cases[id].lastResult});}else if(event.type==='present'){for(const field of ['person','topic','evidenceA','evidenceB'])E.apply(replay,{type:'presentation-select',field,value:event[field]});E.apply(replay,{type:'present'});entries.push({speaker:(c().suspects||[]).find(p=>p.id===event.person)?.name||'',result:replay.cases[id].lastResult});}else if(event.type==='compare'){for(const field of ['left','right'])E.apply(replay,{type:'compare-select',field,value:event[field]});E.apply(replay,{type:'compare'});}else if(event.type==='reconstruct'){for(const [key,value]of Object.entries(event.answers||{}))E.apply(replay,{type:'answer',id:key,value});E.apply(replay,{type:'submit',formId:event.formId});}}show('会話履歴',`<p class="control-help">記録に残った会話を、聞いた順に読み返せます。同じ会話はまとめて表示します。</p><div class="conversation-history">${entries.filter(e=>e.result).map(e=>`<section><h3>${esc(e.speaker)}</h3>${paragraphs(e.result.body)}</section>`).join('')||'<p>まだ記録された会話はありません。</p>'}</div>`);}
function showResult(){if(app.contains(document.activeElement)&&document.activeElement!==app)return;const next=app.querySelector('.object-surface .search-action')||app.querySelector('.object-card[aria-pressed="true"]')||document.getElementById('field-observation-result')||document.getElementById('observation-result');next?.focus({preventScroll:true});}

function inspect(){const ls=locations(),l=ls.find(l=>l.id===p().location);return `<div class="investigation-layout"><aside class="location-list"><h2>調べる場所</h2>${ls.map((l,i)=>btn(`<span>${i+1}</span> ${esc(l.name)}`,'location',`data-id="${l.id}" data-focus-key="location-${l.id}" aria-pressed="${p().location===l.id}"`,'location-choice')).join('')}</aside><section class="location-panel evidence-sheet" id="location-panel" tabindex="-1">${l?`<p class="scene-eyebrow">FIELD NOTES</p><h2>${esc(l.name)}</h2><p>${esc(l.description)}</p>${l.id==='church'||l.id==='church-storage'?btn('中を見渡す','location',`data-id="${l.id}"`,'primary'):''}<div class="search-actions">${l.evidenceIds.map(id=>c().evidence.find(e=>e.id===id)).filter(e=>e&&E.available(c(),p(),e)&&!c().evidence.some(n=>n.supersedes===e.id&&E.available(c(),p(),n))).map(e=>btn(`${p().seen.includes(e.id)?'✓ ':''}${esc(e.action||'調べる')}`,'discover',`data-id="${e.id}" data-focus-key="search-${e.id}"`,'search-action')).join('')}</div><p class="control-help">発見や聞き取りのあと、別の場所や「証言を問い直す」も確かめてみよう。</p>`:'<h2>どこから調べよう？</h2><p>模型の場所、または左の場所名を選んでください。調べたことだけが調査記録に残ります。</p>'}</section></div>${notebook()}`;}
function evidenceBody(e){return `<div class="sheet-top"><span>${esc(e.kind||'調査記録')}</span>${e.supersedes?'<span>問い直したあとの証言</span>':''}</div><h2>${esc(e.title)}</h2>${e.summary?`<p class="sheet-summary">${esc(e.summary)}</p>`:''}${c().id==='future'&&e.art&&window.MysteryArt?window.MysteryArt.evidence(e.art):''}${!voluntary()&&e.inspection?`<figure class="altar-inspection" data-covered="${esc(e.inspection.covered)}" data-uncovered="${esc(e.inspection.uncovered)}"><img class="evidence-detail" src="${esc(e.inspection.covered)}" ${imageAttrs(e.inspection.covered)} alt="祭壇を同じ視点から見た調査画像。白布を掛けた状態"><figcaption>調査時の祭壇・同じ視点</figcaption>${btn('布を上げて見る','inspect-toggle','aria-pressed="false"','primary')}</figure>`:''}${e.image?`<img class="evidence-detail" src="${esc(e.image)}" ${imageAttrs(e.image)} alt="${esc(e.imageAlt||'発見した対象の詳細図')}">`:''}${(e.body||[]).map(t=>`<p>${esc(t)}</p>`).join('')}${e.note?`<p class="evidence-note">${esc(e.note)}</p>`:''}`;}
function notebook(){const items=seen(),e=items.find(e=>e.id===p().selectedEvidence);return `<section class="reading-desk"><aside class="evidence-index"><h2>調査記録${voluntary()?'':` <span>${items.length} 件</span>`}</h2>${items.length?items.map(e=>btn(`${esc(e.title)}${items.some(n=>n.supersedes===e.id)?'<small>以前の証言・保存済み</small>':''}`,'evidence',`data-id="${e.id}" data-focus-key="evidence-${e.id}" aria-pressed="${p().selectedEvidence===e.id}"`,'index-entry')).join(''):'<p>まだ発見はありません</p>'}</aside><article class="evidence-sheet">${e?evidenceBody(e):'<h2>調査記録</h2><p>まだ記録はありません</p>'}</article></section>`;}
function clauseFields(clauses,answers,context='',locked=false){return clauses.map((q,i)=>`<label class="explanation-clause"><span>${i+1}. ${esc(q.prompt)}</span><select data-change="${context?'deduction':'answer'}" data-id="${context||q.id}" data-clause="${q.id}" data-focus-key="clause-${context}-${q.id}" ${locked?'disabled':''}>${opt('','説明の続きを選ぶ',answers?.[q.id])}${q.options.map(o=>opt(o.id,o.text,answers?.[q.id])).join('')}</select></label>`).join('');}
function deductions(){const ds=c().deductions||[],available=ds.filter(d=>E.available(c(),p(),d));return `<div class="deduction-layout"><section><h2>食い違いを言葉にする</h2><p>資料の枚数では、証言は変わりません。つながる説明を選び、本人に問いかけてください。</p>${available.length?available.map(d=>{const r=p().deductions[d.id];return `<article class="deduction-card"><h3>${esc(d.title)}</h3><p>${esc(d.prompt)}</p>${r?.solved?`<p class="revised-response">${esc(d.successText)}</p><p>新しい質問や調べられる場所が増えています。</p>${btn('現場へ戻る','tab','data-tab="inspect"')}`:`${clauseFields(d.clauses,r?.answers,d.id,p().solved)}${btn('この説明で問いかける','deduce',`data-id="${d.id}" ${p().solved?'disabled':''}`,'primary')}`}</article>`;}).join(''):'<p class="empty-investigation">まだ問い直す材料がありません。現場を調べ、関係者の話を聞いてみよう。</p>'}${!ds.length?'<p>この事件には段階的な問い直しはありません。発見した資料を「推理をつなぐ」で整理してください。</p>':''}</section>${reference()}</div>`;}
function reference(){return `<aside class="reference-rail"><h2>発見した資料</h2>${seen().map(e=>btn(esc(e.title),'show-evidence',`data-id="${e.id}" data-focus-key="ref-${e.id}"`,'reference-entry')).join('')||'<p>まだありません</p>'}</aside>`;}
function reconstruction(){return `<div class="report-layout"><div class="reconstruction-sheets">${[['transfer',c().transferReconstruction],['sequence',c().reconstruction]].filter(([,r])=>r).map(([id,r])=>`<article class="report-sheet"><h2>${esc(r.title)}</h2>${E.reconstructionReady(c(),p(),id)?`${clauseFields(r.clauses,p().answers,'',p().resolved.includes(id))}${btn(p().resolved.includes(id)?'解決記録':id==='transfer'?'原本の説明を残す':'機器の説明を残す',p().resolved.includes(id)?'ending':'submit',`data-form-id="${id}" data-focus-key="reconstruct-${id}"`,'primary')}`:'<p>まだ書き込める記録がありません。</p>'}</article>`).join('')}</div>${reference()}</div>`;}
function report(){if((c().requiredFlags||[]).some(f=>!p().flags.includes(f))||(c().requiredEvidence||[]).some(id=>!p().seen.includes(id)))return `<section class="report-sheet"><h2>まだ語られていないことがある</h2><p>今の証言のままでは、事件全体を説明できません。未確認の場所や新しい聞き取りを確かめてから、結論をまとめよう。</p>${btn('現場を調べる','tab','data-tab="inspect"','primary')}${c().deductions?.length?btn('証言を問い直す','tab','data-tab="build"'):''}</section>${reference()}`;return `<div class="report-layout"><article class="report-sheet"><div class="sheet-top"><span>事件 ${c().number} / 調査報告</span><span>提出 ${p().attempts} 回</span></div><h2>一つの説明として、推理をつなぐ</h2><p>証拠の番号ではなく、起きたことの説明を選んでください。全体がつながるまで、各項目の正誤は表示しません。</p>${clauseFields(c().clauses||[],p().answers,'',p().solved)}<div class="report-submit">${btn('現場に戻る','tab','data-tab="inspect"')}${btn(p().solved?'解決記録を読む':'推理を提出する',p().solved?'ending':'submit','','primary')}</div></article>${reference()}</div>`;}
function opening(){const shots=c().opening||[],shot=shots[Math.min(filmIndex,shots.length-1)];return `<main class="opening-screen"><header class="desk-header"><span>序幕 / ${filmIndex+1}・${shots.length}</span>${btn('序幕を飛ばして調査へ','skip-opening')}</header>${scene(true)}<section class="film-subtitles" aria-live="polite"><p class="film-speaker">${esc(shot?.speaker)}</p><p>${esc(shot?.text)}</p></section><footer class="film-controls">${btn('前の場面','film-prev',filmIndex===0?'disabled':'')}${btn(filmPaused?'自動再生する':'一時停止','film-pause')}${btn(filmIndex===shots.length-1?'調査を始める':'次の場面','film-next','','primary')}</footer><p class="control-help">音声なし・字幕つき。省略しても調査に必要な情報は失われません。動きを減らす設定では手動で進みます。</p></main>`;}
function nextShot(){if(filmIndex<(c().opening?.length||0)-1){filmIndex++;render();}else act({type:'skip-opening'});}
function ending(){if(voluntary()){const resolved=(c().incidents||[]).filter(i=>(p().resolved||[]).includes(i.id)),allowed=E.endingParagraphs?.(c(),p()),segments=(c().endingSegments||[]).filter(s=>(!allowed||allowed.includes(s.text))&&E.available(c(),p(),s)&&(!s.resolved||p().resolved.includes(s.resolved))&&(!s.incident||p().resolved.includes(s.incident)));return `<main class="ending-screen"><div class="ending-top">${btn('事件一覧','home')}${btn('調査を続ける','open','','primary')}</div><article class="ending-paper"><p>事件 ${c().number} / ここまでの解決記録</p><h1>${esc(c().title)}</h1>${resolved.map(i=>`<section class="incident-record"><h2>${esc(i.title)}</h2>${segments.filter(s=>(s.incident||s.resolved)===i.id).map(s=>paragraphs(s.text)).join('')}</section>`).join('')}${segments.filter(s=>!s.incident&&!s.resolved).map(s=>paragraphs(s.text)).join('')}<p class="control-help">気になる場所や、まだ聞きたいことがあれば、調査を続けられます。</p>${btn('調査を続ける','open','','primary')}</article></main>`;}return `<main class="ending-screen"><div class="ending-top">${btn('事件一覧','home')}${btn('調査記録に戻る','open')}</div><article class="ending-paper"><p>事件 ${c().number} / 解決記録</p><h1>${esc(c().title)}</h1><p class="ending-lead">${esc(c().ending.lead)}</p>${c().ending.paragraphs.map(t=>`<p>${esc(t)}</p>`).join('')}${btn('同じ事件を最初から','reset')}<a class="primary legacy-launch" href="future-v2.html">近未来の事件へ</a></article></main>`;}

function epilogue(){return `<main class="epilogue-screen"><article><h1>記録の外の足跡</h1><p>書かれたことと、見たこと。語られなかった事情。二つの調査記録を閉じる。</p>${btn('記録室へ','home')}</article></main>`;}
function show(title,body,footer=''){if(!dialog.open){returnFocus=document.activeElement?.dataset.focusKey||'';returnFocusElement=document.activeElement;dialogViewport=viewportSnapshot();}content.innerHTML=`<header class="dialog-header"><h2 id="dialog-title">${esc(title)}</h2>${btn('閉じる','close-dialog')}</header><div class="dialog-body">${body}</div><footer class="dialog-footer">${footer}</footer>`;if(!dialog.open){if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');}dialog.querySelector('button,select,textarea')?.focus({preventScroll:true});restoreViewport(dialogViewport,false);}
function close(){if(dialog.close)dialog.close();else dialog.removeAttribute('open');const el=focusKeyElement(returnFocus)||(returnFocusElement?.isConnected?returnFocusElement:null);el?.focus({preventScroll:true});restoreViewport(dialogViewport,false);dialogViewport=null;returnFocusElement=null;}
dialog.addEventListener('cancel',event=>{event.preventDefault();close();});
function hints(){const total=(c().hints||[]).length;show('段階ヒント',`<p>任意です。最後のヒントは結論を含みます。</p>${(c().hints||[]).slice(0,p().hints).map(([title,text],i)=>`<section class="hint-sheet"><small>${i+1} / ${total}</small><h3>${esc(title)}</h3><p>${esc(text)}</p></section>`).join('')||'<p>まだ開いていません</p>'}`,p().hints<total?btn(p().hints===total-1?'結論のヒントを開く':'次のヒントを開く','hint-next','','primary'):'');}
function exportSave(){const bundle=JSON.parse(E.serialize(state));try{const legacy=localStorage.getItem('record-and-body.future.legacy-v2')||pendingLegacyBackup;if(legacy)bundle.legacyFuture=JSON.parse(legacy);}catch(_){}const blob=new Blob([JSON.stringify(bundle)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='kiroku-to-ashiato-save.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);notice('進行ファイルのダウンロードを開始しました');}
document.addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target||target.disabled)return;const {action,id,caseId,tab}=target.dataset;
 switch(action){
 case 'open':if(dialog.open)close();delete workspaces[caseId||state.current];sceneFocus=null;filmIndex=0;filmPaused=false;act({type:'open',caseId:caseId||state.current});break;
 case 'home':if(dialog.open)close();sceneFocus=null;act({type:'home'});break;
 case 'workspace':{const next=target.dataset.workspace;if(next==='inference'&&p().tab==='inspect')act({type:'tab',tab:'build'},false);switchWorkspace(next);break;}
 case 'tab':workspaces[state.current]=tab==='inspect'?'inspect':'inference';act({type:'tab',tab});break;
 case 'menu':fieldMenu();break;
 case 'premise':show('事件の前提',paragraphs(c().premise));break;
 case 'locations':show('場所を選ぶ',`<div class="location-list">${locations().map(l=>btn(esc(l.name),'location',`data-id="${esc(l.id)}" data-focus-key="location-${esc(l.id)}" aria-pressed="${p().location===l.id}"`,'location-choice')).join('')}</div>`);break;
 case 'sheet-toggle':sheetState[state.current]=sheetState[state.current]===false;render();break;
 case 'talk-records':workspaces[state.current]='inference';act({type:'presentation-select',field:'person',value:id},false);act({type:'tab',tab:'report'});break;
 case 'history':showHistory();break;
 case 'location':if(dialog.open)close();chooseLocation(id);break;
 case 'object':sheetState[state.current]=true;act({type:'object',id});break;
 case 'interact':act({type:'interact',id});showResult();break;
 case 'compare':act({type:'compare'});showResult();break;
 case 'present':act({type:'present'});showResult();break;
 case 'discover':{const before=p().seen.length;act({type:'discover',id});const e=c().evidence.find(e=>e.id===id);if(p().seen.includes(id)){show(e.title,evidenceBody(e),btn('調査に戻る','close-dialog','','primary'));if(p().seen.length>before)notice('調査記録に追加しました');}break;}
 case 'inspect-toggle':{const figure=target.closest('.altar-inspection'),open=target.getAttribute('aria-pressed')!=='true';figure.querySelector('img').src=open?figure.dataset.uncovered:figure.dataset.covered;figure.querySelector('img').alt='祭壇を同じ視点から見た調査画像。'+(open?'白布を上げた状態':'白布を掛けた状態');target.setAttribute('aria-pressed',String(open));target.textContent=open?'布を戻す':'布を上げて見る';break;}
 case 'evidence':act({type:'evidence',id});break;
 case 'show-evidence':{const e=seen().find(e=>e.id===id);if(e)show(e.title,evidenceBody(e));break;}
 case 'deduce':{act({type:'deduce',id});const d=c().deductions.find(d=>d.id===id);if(p().deductions[id]?.solved){show('言葉が変わる',`<p>${esc(d.successText)}</p><p>現場に戻り、新しい話や場所を確かめよう。以前の証言も記録に残ります。</p>`,btn('現場へ戻る','continue-investigation','','primary'));}else show('まだ説明がつながらない','<p>その説明では、見たことと語られたことの食い違いを説明しきれません。選択やメモは残っています。</p>');break;}
 case 'continue-investigation':close();workspaces[state.current]='inspect';act({type:'tab',tab:'inspect'});break;
 case 'submit':act({type:'submit',formId:target.dataset.formId});if(state.screen!=='ending')show('説明を残せませんでした','<p>今の説明は記録と一致していません。選択は残っています。</p>');break;
 case 'notes':show('調査手帳',`<label for="notes-dialog-input">自分のメモ</label><textarea id="notes-dialog-input" rows="10" maxlength="5000" data-change="notes">${esc(p().notes)}</textarea><p>自動保存。最大5,000文字。</p>`);break;
 case 'hints':hints();break;
 case 'hint-next':act({type:'hint'},false);hints();break;
 case 'help':show('遊び方',voluntary()?'<p>場所から物や人を選び、気になった行動を試してみよう。近づくだけでは調査記録は増えません。実際に調べたり、話を聞いたりして分かったことが手帳に残ります。</p><p>手帳の二つの記録は「記録を比べる」で並べられます。「相手に確かめる」では、いつでも人と話題を選び、記録を二つまで示せます。記録がなくても話せます。</p><p>見当が違っても、記録やメモは失われません。解決記録を読んだあとも、ほかの気になることを調べられます。ヒントは任意です。模型と見取り図で同じ調査ができます。</p>':'<p>場所を選び、対象を調べたり人に質問したりします。発見した内容だけが調査記録に残ります。</p><p>食い違いが見つかったら「証言を問い直す」へ。説明を組み立てると、証言や調べられる場所が変わります。読んだ枚数だけでは進みません。</p><p>最後は「推理をつなぐ」で説明文を完成させます。近未来の事件には段階的な問い直しはありません。ヒントは任意です。模型と見取り図で同じ調査ができます。</p>');break;
 case 'close-dialog':close();break;
 case 'replay':if(dialog.open)close();filmIndex=0;filmPaused=false;act({type:'opening'});break;
 case 'skip-opening':act({type:'skip-opening'});break;
 case 'film-next':nextShot();break;
 case 'film-prev':filmIndex=Math.max(0,filmIndex-1);render();break;
 case 'film-pause':filmPaused=!filmPaused;render();break;
 case 'ending':if(dialog.open)close();act({type:'ending',caseId:caseId||state.current});break;
 case 'epilogue':act({type:'epilogue'});break;
 case 'reset':show('この事件を初めから？','<p>この事件の発見、推理、メモ、解決記録を消します。もう一つの事件は残ります。必要なら先に進行をファイル保存してください。</p>',btn('やめる','close-dialog')+btn('この事件を初めから','confirm-reset','','danger'));break;
 case 'confirm-reset':close();act({type:'reset'});break;
 case 'export':exportSave();break;
 case 'import':{let input=document.getElementById('save-import');if(!input){input=document.createElement('input');input.type='file';input.id='save-import';input.accept='application/json,.json';input.hidden=true;document.body.append(input);}input.value='';input.click();break;}
 }
});
document.addEventListener('change',event=>{const el=event.target;if(el.dataset.change==='field-location'&&el.value)chooseLocation(el.value);if(['compare-select','presentation-select'].includes(el.dataset.change))act({type:el.dataset.change,field:el.dataset.field,value:el.value});if(el.dataset.change==='answer')act({type:'answer',id:el.dataset.id,value:el.value});if(el.dataset.change==='deduction')act({type:'deduction-answer',id:el.dataset.id,clause:el.dataset.clause,value:el.value});
 if(el.id==='save-import'){const file=el.files?.[0];if(!file)return;if(file.size>1000000){notice('保存ファイルが大きすぎます');return;}const reader=new FileReader();reader.onload=()=>{try{const raw=JSON.parse(reader.result);if(![1,2,3,4,5].includes(raw?.version)||!D.caseIds.every(id=>raw.cases?.[id]&&typeof raw.cases[id]==='object'))throw new Error('format');const replacement=E.normalizeSave(raw);show('保存ファイルを読み込む？','<p>現在の進行を、このファイルの進行に置き換えます。v4の村は引き継ぎます。旧版の近未来とv1〜v3の村は、メモを残して新版を初めからにします。旧近未来の保存は別に残します。</p>',btn('やめる','close-dialog')+btn('読み込む','confirm-import','','primary'));dialog.querySelector('[data-action="confirm-import"]').addEventListener('click',()=>{close();state=replacement;filmIndex=0;pendingLegacyBackup='';try{if(raw.legacyFuture?.version===2&&raw.legacyFuture.cases?.future)localStorage.setItem('record-and-body.future.legacy-v2',JSON.stringify(raw.legacyFuture));else if(raw.version===2)localStorage.setItem('record-and-body.future.legacy-v2',JSON.stringify(raw));}catch(_){notice('近未来の進行コピーを保存できませんでした');}persist();render();notice('保存ファイルを読み込みました');},{once:true});}catch(_){notice('このゲームの有効な保存ファイルではありません');}};reader.onerror=()=>notice('保存ファイルを読めませんでした');reader.readAsText(file);}
});
document.addEventListener('input',event=>{if(event.target.dataset.change==='notes'){act({type:'notes',value:event.target.value},false);document.querySelectorAll('textarea[data-change="notes"]').forEach(el=>{if(el!==event.target)el.value=p().notes;});}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!dialog.open&&state.screen==='desk'){if(workspace()!=='inspect'){switchWorkspace('inspect');focusKeyElement('workspace-inspect')?.focus({preventScroll:true});}else if(sheetState[state.current]!==false){sheetState[state.current]=false;render();focusKeyElement('sheet-toggle')?.focus({preventScroll:true});}}});
window.addEventListener('pagehide',()=>{persist();clearTimeout(filmTimer);});
render();window.MysteryApp={getState:()=>JSON.parse(E.serialize(state))};
})();
